#!/usr/bin/env bash
# Install SpockD3D9 PE d3d9.dll + dxvk.conf into a Windows D3D9 game directory.
#
# Usage:
#   ./scripts/prepare-steam-d3d9-host.sh \
#     --game-dir "/path/to/game" \
#     --profile tools/fallout3/fallout3.dxvk.conf \
#     --title "Fallout 3"
#
# Options:
#   --game-dir DIR   Game install directory (required)
#   --profile PATH   dxvk.conf source (required)
#   --title NAME     Human-readable title for generated env comments
#   --dll PATH       SpockD3D9 d3d9.dll (default from --arch)
#   --arch x86|x64   DLL bitness when --dll is omitted (default: x86)
#   --build          Run scripts/build-pe-d3d9.sh if DLL is missing

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GAME_DIR=""
PROFILE_PATH=""
TITLE="D3D9 game"
DLL_PATH=""
ARCH="x86"
DO_BUILD=0

usage() {
  cat <<EOF
Usage: $(basename "$0") --game-dir DIR --profile PATH [options]

Copy SpockD3D9 d3d9.dll and a title profile (as dxvk.conf) into DIR.
Writes spockd3d9-host.env for launch-steam-d3d9-host.sh.

Options:
  --title NAME     Human-readable title (default: "$TITLE")
  --dll PATH       SpockD3D9 d3d9.dll (default: build-pe-d3d9-x86 or -x64/d3d9.dll)
  --arch x86|x64   DLL bitness when --dll is omitted (default: x86)
  --build          Build the PE DLL if missing
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --game-dir) shift; GAME_DIR="${1:-}" ;;
    --profile) shift; PROFILE_PATH="${1:-}" ;;
    --title) shift; TITLE="${1:-}" ;;
    --dll) shift; DLL_PATH="${1:-}" ;;
    --arch) shift; ARCH="${1:-}" ;;
    --build) DO_BUILD=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
  shift
done

if [ -z "$GAME_DIR" ]; then
  echo "error: --game-dir is required." >&2
  usage >&2
  exit 1
fi

if [ -z "$PROFILE_PATH" ]; then
  echo "error: --profile is required." >&2
  usage >&2
  exit 1
fi

case "$ARCH" in
  x86|x64) ;;
  *)
    echo "error: --arch must be x86 or x64 (got: $ARCH)" >&2
    exit 1
    ;;
esac

if [ -z "$DLL_PATH" ]; then
  if [ "$ARCH" = x86 ]; then
    DLL_PATH="$ROOT/build-pe-d3d9-x86/d3d9.dll"
  else
    DLL_PATH="$ROOT/build-pe-d3d9/d3d9.dll"
  fi
fi

if [ ! -d "$GAME_DIR" ]; then
  echo "error: game directory does not exist: $GAME_DIR" >&2
  exit 1
fi

if [ ! -f "$PROFILE_PATH" ]; then
  echo "error: profile not found: $PROFILE_PATH" >&2
  exit 1
fi

if [ ! -f "$DLL_PATH" ]; then
  if [ "$DO_BUILD" -eq 1 ]; then
    "$ROOT/scripts/build-pe-d3d9.sh" --arch "$ARCH"
  else
    echo "error: d3d9.dll not found: $DLL_PATH" >&2
    echo "Run ./scripts/build-pe-d3d9.sh --arch $ARCH or pass --build." >&2
    exit 1
  fi
fi

DLL_FILE_TYPE="$(file "$DLL_PATH")"
if ! printf '%s' "$DLL_FILE_TYPE" | grep -Eq 'PE32\+ executable \(DLL\)|PE32 executable \(DLL\)'; then
  echo "error: $DLL_PATH is not a Windows PE DLL" >&2
  printf '%s\n' "$DLL_FILE_TYPE" >&2
  exit 1
fi

if [ "$ARCH" = x86 ] && printf '%s' "$DLL_FILE_TYPE" | grep -q 'PE32+ executable'; then
  echo "error: $DLL_PATH is a 64-bit DLL, but --arch x86 was requested." >&2
  echo "Rebuild with: ./scripts/build-pe-d3d9.sh --arch x86" >&2
  exit 1
fi

if [ "$ARCH" = x64 ] && printf '%s' "$DLL_FILE_TYPE" | grep -q 'PE32 executable (DLL)'; then
  echo "error: $DLL_PATH is a 32-bit DLL, but --arch x64 was requested." >&2
  echo "Rebuild with: ./scripts/build-pe-d3d9.sh --arch x64" >&2
  exit 1
fi

cp -f "$DLL_PATH" "$GAME_DIR/d3d9.dll"
cp -f "$PROFILE_PATH" "$GAME_DIR/dxvk.conf"

ENV_FILE="$GAME_DIR/spockd3d9-host.env"
cat >"$ENV_FILE" <<EOF
# Generated by scripts/prepare-steam-d3d9-host.sh — source before launching $TITLE.
export WINEDLLOVERRIDES="d3d9=n,b"
export DXVK_CONFIG_FILE="$GAME_DIR/dxvk.conf"
export DXVK_LOG_LEVEL="\${DXVK_LOG_LEVEL:-info}"
# Write d3d9.log into the game directory. Required for Steam launches, which
# start the game detached so its stdout cannot be captured by the launcher.
export DXVK_LOG_PATH="\${DXVK_LOG_PATH:-$GAME_DIR}"
export MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=2
# Optional if the host does not find MoltenVK:
# export DYLD_LIBRARY_PATH="\$(brew --prefix molten-vk)/lib:\$DYLD_LIBRARY_PATH"
#
# Steam overlay (gameoverlayrenderer.dll) also hooks D3D9. For clean first-boot
# diagnostics, launch-steam-d3d9-host.sh --no-overlay disables it, or uncomment:
# export WINEDLLOVERRIDES="\$WINEDLLOVERRIDES;gameoverlayrenderer=d;gameoverlayrenderer64=d"
EOF

echo "Installed SpockD3D9 override for $TITLE into:"
echo "  $GAME_DIR/d3d9.dll"
echo "  $GAME_DIR/dxvk.conf"
echo "  $ENV_FILE"
echo ""
echo "Next: ./scripts/launch-steam-d3d9-host.sh --game-dir \"$GAME_DIR\" ..."
echo "Guide: docs/BOOT_TO_MENU.md"
